# This is a basic workflow to help you get started with Actions

name: merge_status

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issue_comment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: logging
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
