# This is a basic workflow to help you get started with Actions

name: set_merge_status

on:
  pull_request:
    branches: [ master ]
    types: [ opened, reopened ]

jobs:
  set_merge_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - run: npm install --save-dev node-fetch
      - run: SHA="${{ github.event.pull_request.head.sha }}" TOKEN="${{ secrets.STATUS_TOKEN }}" node scripts/set-status.js
